
/******************************************************************************
 * INCLUDES
******************************************************************************/
#include <stdio.h>
#include <stdbool.h>
#include <math.h>
#include "FIR_LMS.h"




/* Main */
int main ()
{

	FILE *file_MatlabInput;
	FILE *file_MatlabInputNoise;
	FILE *file_MatlabInputEstimate;
	FILE *file_FirFilterOutput;

	float MatlabInput[N];
	float MatlabInputNoise[N];
	float MatlabInputEstimate[N];

	int FIR_N_Train = 200u;
	float FIR_mu;
	float FIR_inputEstimate[N] = {0};



	/* Read input files generated by Matlab */
	file_MatlabInput = fopen("inp.txt", "r");
	file_MatlabInputNoise = fopen("yn.txt", "r");
	file_MatlabInputEstimate = fopen("inpest.txt", "r");
	int i;
	for(i = 0; i < N; i++)
	{
		fscanf(file_MatlabInput, "%f\n", &MatlabInput[i]);
		fscanf(file_MatlabInputEstimate, "%f\n", &MatlabInputEstimate[i]);
		fscanf(file_MatlabInputNoise, "%f\n", &MatlabInputNoise[i]);
	}
	fclose(file_MatlabInput);
	fclose(file_MatlabInputNoise);
	fclose(file_MatlabInputEstimate);



	/* apply the filter on the input values from matlab */
	int n;
	FIR_mu = 0.52;
	bool isTraining = true;
	for (n = 0; n < N; n++)
	{
		if(n == (FIR_N_Train))
		{
			isTraining = false;
		}
		if(n == 19) /* Slow down convergence */
		{
			FIR_mu = 0.22;
		}
		FIR_LMS(&FIR_inputEstimate[n], &MatlabInputNoise[n], FIR_mu, &MatlabInput[n], isTraining);
	}



	/* check for errors and print results */
	float accumulatedError = 0.0f;
	file_FirFilterOutput = fopen("C:/Vivado_HLS_Tutorial/Laboratoires/Lab_A1/output.txt", "w");
	for(i = 0; i < N; i++)
	{
		accumulatedError += fabs(FIR_inputEstimate[i] - MatlabInputEstimate[i]);
		fprintf(file_FirFilterOutput, "%f\n", FIR_inputEstimate[i]);
		fprintf(stdout, "%d    %0.8f    %0.8f\n", i, FIR_inputEstimate[i], MatlabInputEstimate[i]);
	}
	fclose(file_FirFilterOutput);



	/* check if test passed */
	if(accumulatedError > 0.001f)
	{
		fprintf(stdout, "*******************************************\n");
		fprintf(stdout, "FAIL: Output DOES NOT match the Matlab output\n");
		fprintf(stdout, "*******************************************\n");
	}
	else
	{
		fprintf(stdout, "*******************************************\n");
		fprintf(stdout, "PASS: The output matches the Matlab output!\n");
		fprintf(stdout, "*******************************************\n");
	}

	fprintf(stdout, "Accumulated |error|: %.8f\n", accumulatedError);
	fprintf(stdout, "Average error:       %.8f\n", accumulatedError/(float)N);

	return 0;
}
